[package]
name = "everos"
version = "0.1.0"
authors = ["xermicus <bigcyrill@hotmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.3"
volatile = "0.2.6"  
lazy_static = { version = "1.4", features = ["spin_no_std"] }
spin = "0.5.2"
